= Reactive Relational Database Connectivity H2 Implementation

This project contains the https://www.h2database.com/html/main.html[H2] implementation of the https://github.com/r2dbc/r2dbc-spi[R2DBC SPI].
This implementation is not intended to be used directly, but rather to be used as the backing implementation for a humane client library.

This driver provides the following features:

* Filesystem or in-memory instances
* Explict transactions
* Execution of prepared statements with bindings
* Execution of batch statements without bindings
* Read and write support for all data types except LOB types (e.g. `BLOB`, `CLOB`)

WARNING: Since this driver runs on top of the internals of H2, there is risk of change.
`r2dbc-h2` does not guarantee compatibility except against the version of H2 found in the build file.
Because various parts of H2 are blocking, like file and network access, the only non-blocking assurances are in the layers above H2.
Nevertheless, `r2dbc-h2` is a great way to warm up to the usage of R2DBC with a small footprint.

== Maven

Artifacts can be found on https://search.maven.org/search?q=r2dbc-h2[Maven Central].

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-h2</artifactId>
  <version>0.8.0.RELEASE</version>
</dependency>
----

== Usage

Configuration of the `ConnectionFactory` can be accomplished in two ways:

=== Connection Factory Discovery

[source,java]
----
ConnectionFactory connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
   .option(DRIVER, "h2")
   .option(PROTOCOL, "...")  // file, mem
   .option(DATABASE, "...")
   .build());

Mono<Connection> connection = connectionFactory.create();
----

Supported Connection Factory Discovery options:

[cols="1,5",options="header"]
|===
|Option
|Description

|`driver`
|Must be `h2`

|`protocol`
|Must be `file`, mem`, or `tcp`. Requires `database` if set. _(Optional)_ if `url` set.

|`url`
|A fully qualified H2 URL. _(Optional)_ if `procotol` and `database` are set.

|`username`
|Login username

|`password`
|Login password

|`options`
|A semicolon-delimited list of configuration options. _(Optional)_
|===

=== Programmatic

[source,java]
----
ConnectionFactory connectionFactory = new H2ConnectionFactory(H2ConnectionConfiguration.builder()
    .inMemory("...")
    .option(H2ConnectionOption.DB_CLOSE_DELAY, "-1")
    .build());

Mono<Connection> connection = connectionFactory.create();
----

==== Setting query params

H2 uses index parameters that are prefixed with `$`.
The following SQL statement makes use of parameters:

[source,sql]
----
INSERT INTO person (id, first_name, last_name) VALUES ($1, $2, $3)
----

Parameters are referenced using the same identifiers when binding these:

[source,java]
----
connection
    .createStatement("INSERT INTO person (id, first_name, last_name) VALUES ($1, $2, $3)")
    .bind("$1", 1)
    .bind("$2", "Walter")
    .bind("$3", "White")
    .execute()
----

===== Geometry support

`r2dbc-h2` will automatically register support for https://locationtech.github.io/jts/[JTS Toplogy Suite] and handle it's `Geometry` types if `org.locationtech.jts:jts-core` is on the classpath.

To enable, add this to your build:

[source,xml]
----
<dependency>
    <groupId>org.locationtech.jts</groupId>
    <artifactId>jts-core</artifactId>
    <version>${jts.version}</version>
</dependency>
----

IMPORTANT: Be sure to plug in your version of JTS!

Also read https://h2database.com/html/datatypes.html#geometry_type[H2's reference documentation] on `GEOMETRY` types.

===== We also support params binding as

* index `bind(1, "Walter")`.
Notice that passing an integer means index (zero-based) references.
* $ symbol `bind("$2", "Walter")`.
H2 supports postgres params notation.
* Object (Integer) `bind(yourIntegerAsObject, "Walter")`.
If you index (int) was converted into object by a framework

=== Running JMH Benchmarks

Running the JMH benchmarks builds and runs the benchmarks without running tests.

[source,bash]
----
 $ ./mvnw clean install -Pjmh
----

== License

This project is released under version 2.0 of the https://www.apache.org/licenses/LICENSE-2.0[Apache License].
