= Reactive Relational Database Connectivity H2 Implementation

This project contains the https://www.h2database.com/html/main.html[H2] implementation of the https://github.com/r2dbc/r2dbc-spi[R2DBC SPI]. This implementation is not intended to be used directly,
 but rather to be used as the backing implementation for a humane client library.

This driver provides the following features:

* Filesystem or in-memory instances
* Explict transactions
* Execution of prepared statements with bindings
* Execution of batch statements without bindings
* Read and write support for all data types except LOB types (e.g. `BLOB`, `CLOB`)

== Maven

Both milestone and snapshot artifacts (library, source, and javadoc) can be found in Maven repositories.

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-h2</artifactId>
  <version>1.0.0.BUILD-SNAPSHOT</version>
</dependency>
----

Artifacts can be found at the following repositories.

=== Repositories

[source,xml]
----
<repository>
    <id>spring-snapshots</id>
    <name>Spring Snapshots</name>
    <url>https://repo.spring.io/snapshot</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
----

[source,xml]
----
<repository>
    <id>spring-milestones</id>
    <name>Spring Milestones</name>
    <url>https://repo.spring.io/milestone</url>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>
----

== Usage

Configuration of the `ConnectionFactory` can be accomplished in two ways:

=== Connection Factory Discovery

[source,java]
----
ConnectionFactory connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
   .option(DRIVER, "h2")
   .option(PROTOCOL, "...")  // file, mem
   .option(DATABASE, "...")
   .build());

Mono<Connection> connection = connectionFactory.create();
----

Supported Connection Factory Discovery options:

[cols="1,5", options="header"]
|===
|Option
|Description

|`driver`
|Must be `h2`

|`protocol`
|Must be `file` or `mem`. Requires `database` if set. _(Optional)_ if `url` set.

|`url`
|A fully qualified H2 URL. _(Optional)_ if `procotol` and `database` are set.

|`username`
|Login username

|`password`
|Login password

|`options`
|A semicolon-delimited list of configuration options. _(Optional)_
|===

=== Programmatic

[source,java]
----
ConnectionFactory connectionFactory = new H2ConnectionFactory(H2ConnectionConfiguration.builder()
    .inMemory("...")
    .build());

Mono<Connection> connection = connectionFactory.create();
----

==== Setting query params
H2 uses index parameters that are prefixed with `$`. The following SQL statement makes use of parameters:

[source,sql]
----
INSERT INTO person (id, first_name, last_name) VALUES ($1, $2, $3)
----

Parameters are referenced using the same identifiers when binding these:

[source,java]
----
connection
    .createStatement("INSERT INTO person (id, first_name, last_name) VALUES ($1, $2, $3)")
    .bind("$1", 1)
    .bind("$2", "Walter")
    .bind("$3", "White")
    .execute()
----

===== We also support params binding as

* index `bind(1, "Walter")`. Notice that passing an integer means index (zero-based) references.
* $ symbol `bind("$2", "Walter")`. H2 supports postgres params notation.
* Object (Integer) `bind(yourIntegerAsObject, "Walter")`. If you index (int) was converted into object by a framework

== License

This project is released under version 2.0 of the https://www.apache.org/licenses/LICENSE-2.0[Apache License].